// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Project Overview & Setup',
      collapsed: true,
      items: [
        'Documentations/intro',
        'Documentations/tech-stack',
        {
          type: 'category',
          label: 'Code Structure',
          collapsed: true,
          items: [
            'Documentations/structure/index',
            'Documentations/structure/web',
            'Documentations/structure/api-backend',
            'Documentations/structure/mobile',
          ],
        },
        {
          type: 'category',
          label: 'Installations',
          collapsed: true,
          items: [
            'Documentations/installation/index',
            {
              type: 'category',
              label: 'Web',
              collapsed: true,
              items: [
                'Documentations/installation/web/index',
              ],
            },
            {
              type: 'category',
              label: 'API Backend',
              collapsed: true,
              items: [
                'Documentations/installation/api-backend/index',
                'Documentations/installation/api-backend/restore',
              ],
            },
            {
              type: 'category',
              label: 'Mobile',
              collapsed: true,
              items: [
                'Documentations/installation/mobile/index',
              ],
            },
          ],
        },
        'Documentations/local-setup',
        'Documentations/testing',
        'Documentations/production',
      ],
    },
    {
      type: 'category',
      label: 'Codebase',
      collapsed: true,
      items: [
        'Codebase/Overview',
        {
          type: 'category',
          label: 'API Backend',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Controller',
              collapsed: true,
              items: [
                { type: 'autogenerated', dirName: 'Codebase/API-Backend/Controller' }
              ],
            },
          ],
        },

      ],
    },
    {
      type: 'category',
      label: 'Legacy',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Legacy' }
      ],
    },
  ],
};

export default sidebars;
