// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Project Overview & Setup',
      collapsed: true,
      items: [
        'Documentations/intro',
        'Documentations/tech-stack',
        {
          type: 'category',
          label: 'Code Structure',
          collapsed: true,
          items: [
            'Documentations/structure/index',
            'Documentations/structure/web',
            'Documentations/structure/mobile',
            'Documentations/structure/api-backend',
          ],
        },
        {
          type: 'category',
          label: 'Installations',
          collapsed: true,
          items: [
            'Documentations/installation/index',
            {
              type: 'category',
              label: 'Web',
              collapsed: true,
              items: [
                'Documentations/installation/web/index',
              ],
            },
            {
              type: 'category',
              label: 'API Backend',
              collapsed: true,
              items: [
                'Documentations/installation/api-backend/index',
                'Documentations/installation/api-backend/restore',
              ],
            },
            {
              type: 'category',
              label: 'Mobile',
              collapsed: true,
              items: [
                'Documentations/installation/mobile/index',
              ],
            },
          ],
        },
        'Documentations/local-setup',
        'Documentations/testing',
        'Documentations/production',
      ],
    },
    {
      type: 'category',
      label: 'Codebase',
      collapsed: true,
      items: [
        'Codebase/Overview',
        {
          type: 'category',
          label: 'Web & API Backend',
          collapsed: true,
          items: [
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Documentation_Index',
                  label: 'Documentation Index',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Business_Technical_Map',
                  label: 'Business ↔ Technical Mapping',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Business_Technical_Overview',
                  label: 'Business Technical Overview',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Documentation_Enhancement_Plan',
                  label: 'Documentation Enhancement Plan',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Version_Notes_Guidelines',
                  label: 'Version Notes Guidelines',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Handoff_Guide',
                  label: 'AVP Handoff Guide',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Repository_Structure',
                  label: 'Repository Structure',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Technology_Stack',
                  label: 'Technology Stack',
                },
                {
                  type: 'doc',
                  id: 'Codebase/API-Backend/Report_Business_Technical_Map',
                  label: 'Report Business-Technical Mapping',
                },
                {
                  type: 'category',
                  label: 'Controller',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/Controller' }
                  ],
                },
                {
                  type: 'category',
                  label: 'Data Dictionary',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/DataDictionary' }
                  ],
                },
                {
                  type: 'category',
                  label: 'Models',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/Models' }
                  ],
                },
                {
                  type: 'category',
                  label: 'Reports',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/Reports' }
                  ],
                },
                {
                  type: 'category',
                  label: 'Services',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/Services' }
                  ],
                },
                {
                  type: 'category',
                  label: 'Workflows',
                  collapsed: true,
                  items: [
                    { type: 'autogenerated', dirName: 'Codebase/API-Backend/Workflows' }
                  ],
                },
          ],
        },
        {
          type: 'category',
          label: 'Mobile',
          collapsed: true,
          items: [
                {
                  type: 'doc',
                  id: 'Codebase/Mobile/Repository_Structure',
                },
          ],
        },

      ],
    },
    {
      type: 'category',
      label: 'Legacy',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Legacy' }
      ],
    },
  ],
};

export default sidebars;
